---
title: "classificationComparision"
author: "Hari"
date: "April 16, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("readr")
library("klaR")
library("MASS")
library("randomForest")
library("caret")

```

```{r}
#LOADING DATA
cancer = read_csv("D:/projects/cc/cancer.csv")
View(cancer)
summary(cancer)
head(cancer)

```
```{r}

# Cleaning the dataset. Removing the patient ID
cancer = cancer[, -1]
View(cancer)
head(cancer)

```
```{r}

# Split dataset into train set, validation set and test set

splitdata <- sample(1:2, size = nrow(cancer), prob = c(0.7, 0.3), replace = T)
```
```{r}
# training set
traindata <- cancer[splitdata == 1, ]

intrain <- sample(1:2, size = nrow(traindata), prob = c(0.7, 0.3), replace = T)

traindata <- traindata[intrain == 1, ]
```
```{r}
# validation set
validset <- traindata[intrain == 2, ]
```
```{r}
# test set
testset <- cancer[splitdata == 2, ] 
```
```{r}
# Applying 10 fold Cross- validation
tcontrol <- trainControl(method = "cv", number = 10)
set.seed(1000)
```
```{r}
# Training Naivebayes Classification Model
NavB <- train(diagnosis ~ ., data = traindata, method = "nb", trControl = tcontrol)
```

```{r}

# Predicting Naivebayes Classification Model
NavPred <- predict(NavB, validset)
NavPred

```
```{r}

# Logisitic Regression
LogReg <- train(diagnosis ~ ., data = traindata, method = "glm", family = binomial,trControl = tcontrol)
```
```{r}
# Logistic Regression
LRPred <- predict(LogReg, validset)
LRPred
```
```{r}
# Making `data` and `reference` to be factors with the same levels.
validset$diagnosis <- as.factor(validset$diagnosis)
levels(validset$diagnosis) <- levels(NavPred)
length(NavPred) <- length(validset$diagnosis)
ConmaxNB <- confusionMatrix(validset$diagnosis, NavPred)
```
```{r}
# Confusion Matrix for Logisitic Regression
length(LRPred) <- length(validset$diagnosis)
ConmaxLG <- confusionMatrix(validset$diagnosis, LRPred)

ModelType <- c( "Naive Bayes", "Logistic regression")  
```
```{r}

# Training classification accuracy
TrainAccuracy <- c(max(NavB$results$Accuracy), 
                    max(LogReg$results$Accuracy))

# Training misclassification error
Train_missclass_Error <- 1 - TrainAccuracy

# validation classification accuracy
ValidationAccuracy <- c( ConmaxNB$overall[1], 
                         ConmaxLG$overall[1])

# Validation misclassification error or out-of-sample-error
Validation_missclass_Error <- 1 - ValidationAccuracy


```
```{r}
Results <- data.frame(ModelType, TrainAccuracy, Train_missclass_Error, ValidationAccuracy, 
                      Validation_missclass_Error)
Results

```
```{r}

## Testing Logistic Regression Model on test data
TestingLG <- predict(LogReg, testset)
TestingLG

```